services:
  model-training:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    network_mode: host
    volumes:
      - "${HOST_PROJECT_ROOT:-../../}:/workspace"
    working_dir: /workspace
    environment:
      - PYTHONPATH=/workspace
    deploy:
      resources:
        limits:
          cpus: '16.0'
          memory: 2G
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
