from importlib import import_module

COMMON_MODULES = [
    'training.batch_size_optimization',
    'training.gradient_accumulation',
    'training.gradient_clipping',
    'training.optimizer_selection',
    'training.optimizer_state_reduction',
    'training.learning_rate_optimization',
    'training.learning_rate_scheduling',
    'training.learning_rate_warmup',
    'training.early_stopping',
    'training.reduce_training_epochs',
    'training.dynamic_epoch_allocation',
    'training.validation_frequency_optimization',
    'training.logging_optimization',
    'training.checkpoint_frequency_optimization',
    'training.checkpoint_resume',
    'training.reproducibility_optimization',
    'data.data_loading_optimization',
    'data.parallel_data_loading',
    'data.data_prefetching',
    'data.dataset_caching',
    'data.memory_mapping',
    'data.sequence_length_optimization',
    'data.sliding_window_optimization',
    'data.padding_optimization',
    'data.sequence_length_bucketing',
    'data.data_pipeline_parallelism',
    'data.io_optimization',
    'model.model_architecture_simplification',
    'model.model_width_depth_scaling',
    'model.transfer_learning',
    'model.layer_freezing',
    'model.parameter_efficient_finetuning',
    'model.knowledge_distillation',
    'model.model_quantization',
    'model.quantization_aware_training',
    'model.model_specific_optimization',
    'model.framework_specific_optimization',
    'hyperparameter.random_search',
    'hyperparameter.bayesian_optimization',
    'hyperparameter.optuna_optimization',
    'hyperparameter.hyperband',
    'hyperparameter.asha',
    'hyperparameter.successive_halving',
    'hyperparameter.trial_pruning',
    'hyperparameter.warm_start_hyperparameter_search',
    'hyperparameter.parallel_experiment_execution',
    'hyperparameter.hyperparameter_budget_control',
    'memory.memory_cleanup',
    'memory.garbage_collection_optimization',
    'memory.memory_fragmentation_control',
    'memory.checkpoint_memory_management',
    'memory.temporary_buffer_optimization',
    'memory.duplicate_memory_copy_reduction',
    'reliability.automatic_retry',
    'reliability.automatic_recovery',
    'reliability.automatic_optimization_rollback',
    'reliability.training_divergence_detection',
    'reliability.nan_infinity_detection',
    'reliability.numerical_stability_checks',
    'reliability.out_of_memory_recovery',
    'reliability.failed_worker_recovery',
    'reliability.checkpoint_integrity_validation',
    'resource_management.resource_aware_scheduling',
    'resource_management.dynamic_resource_scaling',
    'resource_management.resource_isolation',
    'resource_management.job_priority_scheduling',
    'resource_management.cost_aware_optimization',
    'resource_management.constraint_based_optimization',
    'resource_management.accuracy_preserving_optimization',
    'resource_management.optimization_ordering',
    'resource_management.optimization_impact_estimation',
    'resource_management.resource_budget_control',
]


def load_common_strategies():
    result = {}
    for module_name in COMMON_MODULES:
        clean_name = module_name.removeprefix('common.')
        module = import_module(f'.{clean_name}', package=__package__)
        strategy = module.create_strategy()
        result[strategy.spec.name] = strategy
    return result

