import { tool } from "@langchain/core/tools";
import { z } from "zod";
import * as fs from "fs";
import * as path from "path";
import * as yaml from "js-yaml";
import {
  getFileServerBasePath,
  sanitizeFolderName,
} from "../../../config/fileServer.config";

/**
 * Resolves the project root directory for a given project context.
 */
function resolveProjectRoot(
  projectId: string,
  runTimestamp: string,
  projectName: string,
  workspaceName: string
): string {
  return path.join(
    getFileServerBasePath(),
    "workspaces",
    sanitizeFolderName(workspaceName || "Default_Workspace"),
    "projects",
    sanitizeFolderName(projectName || "Forecasting")
  );
}

/**
 * Tool to read and parse the Model Training Report JSON generated by the training agent.
 * Provides candidate model results, test metrics, champion model, and feature information.
 */
export const createReadTrainingReportTool = (
  projectId: string,
  runTimestamp: string,
  projectName: string,
  workspaceName: string
) =>
  tool(
    async () => {
      try {
        const projectRoot = resolveProjectRoot(projectId, runTimestamp, projectName, workspaceName);
        const runDir = runTimestamp ? path.join(projectRoot, runTimestamp) : projectRoot;
        const modelTrainingDir = path.join(runDir, `${projectName}_model_training`);

        const reportCandidates = [
          path.join(modelTrainingDir, "reports", "model_training_report.json"),
          path.join(modelTrainingDir, "model_training_report.json"),
          path.join(runDir, "model_training_report.json"),
        ];

        for (const reportPath of reportCandidates) {
          if (fs.existsSync(reportPath)) {
            const raw = fs.readFileSync(reportPath, "utf-8");
            const report = JSON.parse(raw);
            return {
              success: true,
              reportPath,
              report,
              candidateModels: Object.keys(report.candidate_model_results || {}),
              championModelId: report.selected_model || report.champion_model || null,
              testMetrics: report.candidate_model_results || {},
            };
          }
        }

        return {
          success: false,
          error: `Training report not found for run ${runTimestamp} in project ${projectName}`,
          searchedPaths: reportCandidates,
        };
      } catch (err: any) {
        return {
          success: false,
          error: err?.message || String(err),
        };
      }
    },
    {
      name: "readTrainingReport",
      description:
        "Reads and parses the model_training_report.json from the training directory. Returns candidate model results, test metrics, champion model ID, and feature information.",
      schema: z.object({}),
    }
  );

/**
 * Tool to list trained model artifacts (.joblib) in the models directory
 * and check for preprocessor availability.
 */
export const createReadTrainedModelsMetadataTool = (modelsDir: string) =>
  tool(
    async () => {
      try {
        if (!fs.existsSync(modelsDir)) {
          return {
            success: false,
            error: `Models directory not found: ${modelsDir}`,
            models: [],
            hasPreprocessor: false,
          };
        }

        const allFiles = fs.readdirSync(modelsDir);
        const modelFiles = allFiles.filter(
          (f) =>
            f.endsWith(".joblib") &&
            f !== "preprocessor.joblib" &&
            f !== "selected_model.joblib"
        );

        const models = modelFiles.map((f) => {
          const fullPath = path.join(modelsDir, f);
          const stats = fs.statSync(fullPath);
          return {
            fileName: f,
            modelId: path.basename(f, ".joblib"),
            sizeBytes: stats.size,
            sizeFormatted: `${(stats.size / 1024 / 1024).toFixed(2)} MB`,
          };
        });

        const hasPreprocessor = fs.existsSync(
          path.join(modelsDir, "preprocessor.joblib")
        );

        const hasSelectedModel = fs.existsSync(
          path.join(modelsDir, "selected_model.joblib")
        );

        return {
          success: true,
          modelsDir,
          models,
          modelCount: models.length,
          hasPreprocessor,
          hasSelectedModel,
          allFiles: allFiles,
        };
      } catch (err: any) {
        return {
          success: false,
          error: err?.message || String(err),
          models: [],
          hasPreprocessor: false,
        };
      }
    },
    {
      name: "readTrainedModelsMetadata",
      description:
        "Lists all trained model .joblib artifacts in the models directory, their sizes, and whether a preprocessor.joblib is available.",
      schema: z.object({}),
    }
  );

/**
 * Tool to read the training_config.yaml and any existing validation config
 * to understand dataset schema, split dates, target/time columns, and problem type.
 */
export const createReadValidationConfigTool = (
  modelTrainingDir: string,
  runDir: string
) =>
  tool(
    async () => {
      try {
        // Read training config
        let trainingConfig: Record<string, any> = {};
        const trainingConfigPath = path.join(
          modelTrainingDir,
          "configs",
          "training_config.yaml"
        );
        if (fs.existsSync(trainingConfigPath)) {
          const raw = fs.readFileSync(trainingConfigPath, "utf-8");
          trainingConfig = (yaml.load(raw) as Record<string, any>) || {};
        }

        // Check for existing validation config
        let existingValidationConfig: Record<string, any> | null = null;
        const existingValConfigPath = path.join(
          runDir,
          "model_validation",
          "configs",
          "validation_config.yaml"
        );
        if (fs.existsSync(existingValConfigPath)) {
          const raw = fs.readFileSync(existingValConfigPath, "utf-8");
          existingValidationConfig =
            (yaml.load(raw) as Record<string, any>) || null;
        }

        // Extract key schema info
        const schema = {
          targetColumn:
            trainingConfig?.task?.target_column ||
            trainingConfig?.target_column ||
            null,
          timeColumn:
            trainingConfig?.split?.time_column ||
            trainingConfig?.time_column ||
            null,
          splitDate:
            trainingConfig?.split?.split_date ||
            trainingConfig?.split_date ||
            null,
          splitEndDate:
            trainingConfig?.split?.split_end_date ||
            trainingConfig?.split_end_date ||
            null,
          problemType:
            trainingConfig?.task?.task_type ||
            trainingConfig?.problem_type ||
            null,
          groupBy:
            trainingConfig?.split?.group_by ||
            trainingConfig?.group_by ||
            null,
        };

        return {
          success: true,
          trainingConfigPath,
          trainingConfig,
          schema,
          existingValidationConfig,
        };
      } catch (err: any) {
        return {
          success: false,
          error: err?.message || String(err),
          trainingConfig: {},
          schema: {},
        };
      }
    },
    {
      name: "readValidationConfig",
      description:
        "Reads training_config.yaml and any existing validation configuration. Returns dataset schema details including target column, time column, split dates, problem type, and grouping column.",
      schema: z.object({}),
    }
  );

/**
 * Tool to validate that the expected validation output files exist
 * after the validation runner has been generated/executed.
 */
export const createValidateValidationOutputTool = (
  modelValidationDir: string
) =>
  tool(
    async () => {
      try {
        const expectedFiles = [
          "validation_runner.py",
          path.join("reports", "model_validation_report.json"),
          path.join("artifacts", "predictions", "validation_predictions.parquet"),
          path.join("configs", "validation_config.yaml"),
        ];

        const results: Array<{
          file: string;
          exists: boolean;
          sizeBytes?: number;
        }> = [];
        const missing: string[] = [];
        const present: string[] = [];

        for (const relFile of expectedFiles) {
          const fullPath = path.join(modelValidationDir, relFile);
          const exists = fs.existsSync(fullPath);
          if (exists) {
            const stats = fs.statSync(fullPath);
            results.push({
              file: relFile.replace(/\\/g, "/"),
              exists: true,
              sizeBytes: stats.size,
            });
            present.push(relFile.replace(/\\/g, "/"));
          } else {
            results.push({ file: relFile.replace(/\\/g, "/"), exists: false });
            missing.push(relFile.replace(/\\/g, "/"));
          }
        }

        // Also check if report is valid JSON when present
        let reportValid = false;
        const reportPath = path.join(
          modelValidationDir,
          "reports",
          "model_validation_report.json"
        );
        if (fs.existsSync(reportPath)) {
          try {
            JSON.parse(fs.readFileSync(reportPath, "utf-8"));
            reportValid = true;
          } catch {
            reportValid = false;
          }
        }

        return {
          success: missing.length === 0,
          valid: missing.length === 0,
          presentFiles: present,
          missingFiles: missing,
          fileDetails: results,
          reportValid,
          validationDirectory: modelValidationDir,
        };
      } catch (err: any) {
        return {
          success: false,
          error: err?.message || String(err),
          presentFiles: [],
          missingFiles: [],
        };
      }
    },
    {
      name: "validateValidationOutput",
      description:
        "Validates that all expected validation output files exist: validation_runner.py, model_validation_report.json, validation_predictions.parquet, and validation_config.yaml.",
      schema: z.object({}),
    }
  );
