import { PIPELINE_NAMES, PipelineName } from "./pipelineNames";

export const FEATURE_ENGINEERING_SUBSTEPS: Record<string, PipelineName> = {
  "Hierarchy Mapper": PIPELINE_NAMES.FEATURE_ENGINEERING,
  "hierarchyMapper": PIPELINE_NAMES.FEATURE_ENGINEERING,
  "hierarchyMapperNode": PIPELINE_NAMES.FEATURE_ENGINEERING,
  "Feature Architect": PIPELINE_NAMES.FEATURE_ENGINEERING,
  "featureArchitect": PIPELINE_NAMES.FEATURE_ENGINEERING,
  "featureArchitectNode": PIPELINE_NAMES.FEATURE_ENGINEERING,
  "Feature Validator": PIPELINE_NAMES.FEATURE_ENGINEERING,
  "featureValidator": PIPELINE_NAMES.FEATURE_ENGINEERING,
  "featureValidatorNode": PIPELINE_NAMES.FEATURE_ENGINEERING,
  "Exogenous Scout": PIPELINE_NAMES.FEATURE_ENGINEERING,
  "exogenousScout": PIPELINE_NAMES.FEATURE_ENGINEERING,
  "exogenous": PIPELINE_NAMES.FEATURE_ENGINEERING,
  "Feature Engineering": PIPELINE_NAMES.FEATURE_ENGINEERING,
};
