import { PIPELINE_NAMES, PipelineName } from "./pipelineNames";

export const MODEL_TRAINING_VALIDATION_SUBSTEPS: Record<string, PipelineName> = {
  "Model Selection": PIPELINE_NAMES.MODEL_TRAINING_VALIDATION,
  "modelSelection": PIPELINE_NAMES.MODEL_TRAINING_VALIDATION,
  "modelSelectionNode": PIPELINE_NAMES.MODEL_TRAINING_VALIDATION,
  "Training Configuration": PIPELINE_NAMES.MODEL_TRAINING_VALIDATION,
  "trainingConfiguration": PIPELINE_NAMES.MODEL_TRAINING_VALIDATION,
  "trainingConfigurationNode": PIPELINE_NAMES.MODEL_TRAINING_VALIDATION,
  "Pre Flight": PIPELINE_NAMES.MODEL_TRAINING_VALIDATION,
  "preFlight": PIPELINE_NAMES.MODEL_TRAINING_VALIDATION,
  "preFlightNode": PIPELINE_NAMES.MODEL_TRAINING_VALIDATION,
  "Model Training": PIPELINE_NAMES.MODEL_TRAINING_VALIDATION,
  "modelTraining": PIPELINE_NAMES.MODEL_TRAINING_VALIDATION,
  "modelTrainingNode": PIPELINE_NAMES.MODEL_TRAINING_VALIDATION,
  "Model Evaluation": PIPELINE_NAMES.MODEL_TRAINING_VALIDATION,
  "modelEvaluation": PIPELINE_NAMES.MODEL_TRAINING_VALIDATION,
  "modelEvaluationNode": PIPELINE_NAMES.MODEL_TRAINING_VALIDATION,
  "Model Validation": PIPELINE_NAMES.MODEL_TRAINING_VALIDATION,
  "modelValidation": PIPELINE_NAMES.MODEL_TRAINING_VALIDATION,
  "modelValidationNode": PIPELINE_NAMES.MODEL_TRAINING_VALIDATION,
  "Model Training & Validation": PIPELINE_NAMES.MODEL_TRAINING_VALIDATION,
};
